name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      test_file:
        description: "Test file path (e.g., tests/Assignment.spec.ts or Assignment.spec.ts). Leave empty to run default."
        required: false
        default: ""
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          TEST_FILE="${{ github.event.inputs.test_file }}"
          if [ -z "$TEST_FILE" ]; then
            echo "No test file provided; running default: Assignment.spec.ts"
            TEST_FILE="Assignment.spec.ts"
          else
            echo "Running tests for: $TEST_FILE"
          fi
          npx playwright test "$TEST_FILE" --workers=10
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
